application: deep-castle-94318
module: default
version: v2
runtime: python27
instance_class: F4
threadsafe: true
api_version: 1

handlers:

- url: .*
  script: main.app


env_variables:
  FIREBASE_DB: 'https://nmbdean.firebaseio.com'